# Generated by Django 6.0.6 on 2026-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলা)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('badge_bn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ব্যাজ টেক্সট (বাংলা)')),
                ('badge_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Badge Text (English)')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='ছবি')),
                ('category', models.CharField(choices=[('hsc', 'HSC'), ('ssc', 'SSC'), ('class_678', 'Class 6-8')], max_length=20, verbose_name='ক্যাটাগরি')),
                ('link', models.CharField(default='/', max_length=500, verbose_name='লিংক')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'কোর্স',
                'verbose_name_plural': 'কোর্সসমূহ',
                'ordering': ['order'],
            },
        ),
    ]
