# Generated by Django 6.0.2 on 2026-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ইন্সট্রাক্টর'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('hsc', 'HSC'), ('ssc', 'SSC'), ('class_678', 'Class 6-8'), ('online_english', 'অনলাইন ইংরেজি কোর্স')], max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
