# Generated by Django 6.0.6 on 2026-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('school_college', 'স্কুল ও কলেজ'), ('online_english', 'অনলাইন ইংরেজি কোর্স')], max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
