# Generated by Django 6.0.2 on 2026-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='এলাকার নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Area Name (English)')),
                ('address_bn', models.TextField(verbose_name='ঠিকানা (বাংলা)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'অফলাইন সেন্টার',
                'verbose_name_plural': 'অফলাইন সেন্টারসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('school_college', 'স্কুল ও কলেজ'), ('online_english', 'অনলাইন ইংরেজি কোর্স'), ('offline_english', 'অফলাইন ইংরেজি কোর্স')], max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
