# Generated by Django 6.0.2 on 2026-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_offlinelocation_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=255, verbose_name='শিরোনাম (বাংলা)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('description_bn', models.TextField(verbose_name='বিবরণ (বাংলা)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'অফলাইন ফিচার',
                'verbose_name_plural': 'অফলাইন ফিচারসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OfflineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offline_images/', verbose_name='ছবি')),
                ('caption_bn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ক্যাপশন (বাংলা)')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'অফলাইন ছবি',
                'verbose_name_plural': 'অফলাইন ছবিসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuperFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title (যেমন: SuperLive Class)')),
                ('title_color', models.CharField(default='#38bdf8', max_length=20, verbose_name='Title Color (hex code)')),
                ('description_bn', models.TextField(verbose_name='বিবরণ (বাংলা)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='super_features/', verbose_name='ছবি')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'সুপার ফিচার',
                'verbose_name_plural': 'সুপার ফিচারসমূহ',
                'ordering': ['order'],
            },
        ),
    ]
