# Generated by Django 6.0.2 on 2026-06-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_offlinefeature_offlineimage_superfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200)),
                ('color', models.CharField(default='#f97316', max_length=7)),
                ('gradient_from', models.CharField(default='#1a1000', max_length=7)),
                ('gradient_to', models.CharField(default='#2a1a00', max_length=7)),
                ('border_color', models.CharField(default='#3a2a00', max_length=7)),
                ('grid_cols', models.IntegerField(default=1, help_text='1=single column, 2=span 2 columns')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Batch Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1_en', models.CharField(default="All the Country's Best", max_length=100)),
                ('title_part1_bn', models.CharField(default='দেশসেরা সকল', max_length=100)),
                ('title_part2_en', models.CharField(default='Online', max_length=100)),
                ('title_part2_bn', models.CharField(default='অনলাইন', max_length=100)),
                ('title_part2_color', models.CharField(default='#f97316', max_length=7)),
                ('title_part3_en', models.CharField(default='Batches', max_length=100)),
                ('title_part3_bn', models.CharField(default='ব্যাচ', max_length=100)),
                ('title_part3_color', models.CharField(default='#facc15', max_length=7)),
                ('subtitle_en', models.TextField(default='Become one of the 30,000+ Academic students...')),
                ('subtitle_bn', models.TextField(default='টেন মিনিট স্কুলের বিভিন্ন কোর্সে...')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch Section Heading',
                'verbose_name_plural': 'Batch Section Headings',
            },
        ),
        migrations.CreateModel(
            name='OnlineBatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('color', models.CharField(default='#f97316', max_length=20, verbose_name='Title Color (hex)')),
                ('gradient_from', models.CharField(default='#1a1000', max_length=20, verbose_name='Gradient From Color')),
                ('gradient_to', models.CharField(default='#2a1a00', max_length=20, verbose_name='Gradient To Color')),
                ('border_color', models.CharField(default='#3a2a00', max_length=20, verbose_name='Border Color')),
                ('is_wide', models.BooleanField(default=False, verbose_name='চওড়া? (2 কলাম)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'অনলাইন ব্যাচ ক্যাটাগরি',
                'verbose_name_plural': 'অনলাইন ব্যাচ ক্যাটাগরিসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BatchSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_bn', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.batchcategory')),
            ],
            options={
                'verbose_name_plural': 'Batch Subcategories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=300)),
                ('name_bn', models.CharField(max_length=300)),
                ('has_gift', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.batchsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Batch Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineBatchSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.onlinebatchcategory', verbose_name='ক্যাটাগরি')),
            ],
            options={
                'verbose_name': 'সাবক্যাটাগরি',
                'verbose_name_plural': 'সাবক্যাটাগরিসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলা)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('has_gift', models.BooleanField(default=False, verbose_name='গিফট আইকন (🎁)?')),
                ('link', models.CharField(default='/', max_length=500, verbose_name='লিংক')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.onlinebatchsubcategory', verbose_name='সাবক্যাটাগরি')),
            ],
            options={
                'verbose_name': 'ব্যাচ আইটেম',
                'verbose_name_plural': 'ব্যাচ আইটেমসমূহ',
                'ordering': ['order'],
            },
        ),
    ]
