# Generated by Django 6.0.2 on 2026-06-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_batchcategory_batchsection_onlinebatchcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='batchitem',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='BatchSection',
        ),
        migrations.DeleteModel(
            name='BatchCategory',
        ),
        migrations.DeleteModel(
            name='BatchItem',
        ),
        migrations.DeleteModel(
            name='BatchSubcategory',
        ),
    ]
