# Generated by Django 6.0.2 on 2026-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_batchsubcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(blank=True, max_length=200, null=True, verbose_name='শিরোনাম (বাংলা)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (English)')),
                ('left_scroll_speed', models.FloatField(default=0.5, help_text='Pixels per frame (0.5 = slow, 2 = fast)', verbose_name='Left Banner Speed (→)')),
                ('right_scroll_speed', models.FloatField(default=0.5, help_text='Pixels per frame (0.5 = slow, 2 = fast)', verbose_name='Right Banner Speed (←)')),
                ('image_width_min', models.IntegerField(default=170, verbose_name='Min Width')),
                ('image_width_max', models.IntegerField(default=250, verbose_name='Max Width')),
                ('image_height_min', models.IntegerField(default=120, verbose_name='Min Height')),
                ('image_height_max', models.IntegerField(default=175, verbose_name='Max Height')),
                ('gap_between_images', models.IntegerField(default=12, help_text='Space between images in pixels', verbose_name='Gap (px)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Configuration',
                'verbose_name_plural': 'Banner Configurations',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='ছবি')),
                ('direction', models.CharField(choices=[('left', 'Left to Right Scroll (→)'), ('right', 'Right to Left Scroll (←)')], default='left', max_length=10, verbose_name='Scroll Direction')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['direction', 'order'],
            },
        ),
    ]
