# Generated by Django 6.0.2 on 2026-06-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_bannerconfig_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text_bn', models.TextField(verbose_name='Review (বাংলা)')),
                ('review_text_en', models.TextField(verbose_name='Review (English)')),
                ('student_name_bn', models.CharField(max_length=200, verbose_name='Student Name (বাংলা)')),
                ('student_name_en', models.CharField(max_length=200, verbose_name='Student Name (English)')),
                ('school_name_bn', models.CharField(max_length=300, verbose_name='School (বাংলা)')),
                ('school_name_en', models.CharField(max_length=300, verbose_name='School (English)')),
                ('background_gradient_from', models.CharField(default='#0a1a2a', max_length=20, verbose_name='Background From Color')),
                ('background_gradient_to', models.CharField(default='#051510', max_length=20, verbose_name='Background To Color')),
                ('border_color', models.CharField(default='#1a3a3a', max_length=20, verbose_name='Border Color')),
                ('gender', models.CharField(choices=[('male', 'Male (👦)'), ('female', 'Female (👧)')], default='male', max_length=10, verbose_name='Gender (Icon)')),
                ('is_highlight', models.BooleanField(default=False, verbose_name="Show 'See More' Button?")),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Student Review',
                'verbose_name_plural': 'Student Reviews',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title_bn', models.CharField(default='শিক্ষার্থীদের মতামত', max_length=200, verbose_name='Section Title (বাংলা)')),
                ('section_title_en', models.CharField(default='Student Reviews', max_length=200, verbose_name='Section Title (English)')),
                ('card_width_mobile', models.CharField(default='85vw', max_length=20, verbose_name='Card Width (Mobile)')),
                ('card_width_desktop', models.CharField(default='300px', max_length=20, verbose_name='Card Max Width (Desktop)')),
                ('card_min_height', models.CharField(default='320px', max_length=20, verbose_name='Card Min Height')),
                ('male_icon_url', models.CharField(default='/images/boys_icon.jpg', max_length=500, verbose_name='Male Icon URL')),
                ('female_icon_url', models.CharField(default='/images/girls_icon.jpg', max_length=500, verbose_name='Female Icon URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student Review Configuration',
                'verbose_name_plural': 'Student Review Configurations',
            },
        ),
    ]
